create type quest_difficulty as enum ('Lesser Burden', 'Sinuous Vow', 'Mortal Penance');
create type quest_category as enum ('Vow', 'Trial', 'Crusade', 'General', 'Habit');
create type goal_status as enum ('In Quest', 'Triumphant', 'Abandoned');
create type skill_category as enum ('Programming', 'Fitness', 'Personal Development');
create type skill_node_status as enum ('locked', 'available', 'unlocked');
create type active_rarity as enum ('Common', 'Rare', 'Epic', 'Legendary', 'Mythic');

create table users (
  id text primary key,
  email text not null,
  name text not null,
  display_name text not null,
  preferred_name text,
  title text not null default 'The Wanderer',
  level integer not null default 1,
  xp integer not null default 0 check (xp >= 0),
  streak integer not null default 0 check (streak >= 0),
  avatar_seed text not null default '',
  monument_seed text not null default '',
  date_of_birth date,
  timezone text not null default 'UTC',
  last_assessment text,
  last_assessment_date timestamptz,
  character_profile jsonb not null default '{}'::jsonb,
  account_created timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table user_stats (
  user_id text primary key references users(id) on delete cascade,
  strength integer not null default 10 check (strength between 1 and 100),
  endurance integer not null default 10 check (endurance between 1 and 100),
  discipline integer not null default 10 check (discipline between 1 and 100),
  recovery integer not null default 10 check (recovery between 1 and 100),
  focus integer not null default 10 check (focus between 1 and 100),
  consistency integer not null default 10 check (consistency between 1 and 100),
  learning_speed integer not null default 10 check (learning_speed between 1 and 100),
  resilience integer not null default 10 check (resilience between 1 and 100),
  programming integer not null default 10 check (programming between 1 and 100),
  mathematics integer not null default 10 check (mathematics between 1 and 100),
  finance integer not null default 10 check (finance between 1 and 100),
  communication integer not null default 10 check (communication between 1 and 100),
  creativity integer not null default 10 check (creativity between 1 and 100),
  leadership integer not null default 10 check (leadership between 1 and 100),
  networking integer not null default 10 check (networking between 1 and 100),
  collaboration integer not null default 10 check (collaboration between 1 and 100)
);

create table user_earned_titles (
  id bigint generated by default as identity primary key,
  user_id text not null references users(id) on delete cascade,
  title text not null,
  unlocked_at timestamptz not null default now(),
  unique (user_id, title)
);

create table user_chronicle (
  id text primary key,
  user_id text not null references users(id) on delete cascade,
  timeframe text not null,
  bullet_points text[] not null default '{}',
  created_at timestamptz not null default now()
);

create table user_achievements (
  user_id text not null references users(id) on delete cascade,
  achievement_id text not null,
  name text not null,
  description text not null,
  category text not null,
  rarity active_rarity not null default 'Common',
  unlocked boolean not null default false,
  unlocked_at timestamptz,
  primary key (user_id, achievement_id)
);

create table user_skill_nodes (
  user_id text not null references users(id) on delete cascade,
  category skill_category not null,
  node_id text not null,
  name text not null,
  description text not null,
  level integer not null default 0 check (level >= 0),
  max_level integer not null default 5 check (max_level > 0),
  status skill_node_status not null default 'locked',
  xp integer not null default 0 check (xp >= 0),
  required_xp integer not null default 100 check (required_xp >= 0),
  prerequisites text[] not null default '{}',
  primary key (user_id, category, node_id)
);

create table quests (
  id text primary key,
  user_id text not null references users(id) on delete cascade,
  title text not null,
  description text,
  difficulty quest_difficulty not null default 'Lesser Burden',
  category quest_category not null default 'General',
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  due_date date,
  data jsonb not null default '{}'::jsonb
);

create table goals (
  id text primary key,
  user_id text not null references users(id) on delete cascade,
  title text not null,
  aspiration text not null,
  category_name text not null,
  timeline_explanation text,
  resources text[] not null default '{}',
  status goal_status not null default 'In Quest',
  created_at timestamptz not null default now(),
  linked_quests_added boolean not null default false,
  data jsonb not null default '{}'::jsonb
);

create table goal_stages (
  id bigint generated by default as identity primary key,
  goal_id text not null references goals(id) on delete cascade,
  stage_index integer not null check (stage_index >= 0),
  name text not null,
  lore text,
  unique (goal_id, stage_index)
);

create table goal_tasks (
  id text primary key,
  goal_id text not null references goals(id) on delete cascade,
  stage_index integer not null,
  title text not null,
  description text,
  difficulty quest_difficulty not null default 'Lesser Burden',
  category quest_category not null default 'General',
  day_offset integer not null default 0 check (day_offset >= 0),
  completed boolean not null default false,
  foreign key (goal_id, stage_index) references goal_stages(goal_id, stage_index) on delete cascade
);

create index idx_quests_user_completed on quests(user_id, completed);
create index idx_quests_due_date on quests(due_date);
create index idx_goals_user_status on goals(user_id, status);
create index idx_user_skill_nodes_lookup on user_skill_nodes(user_id, status);
create index idx_user_earned_titles_lookup on user_earned_titles(user_id);
create index idx_quests_payload on quests using gin (data);
create index idx_goals_payload on goals using gin (data);

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger users_set_updated_at
before update on users
for each row execute function set_updated_at();

alter table users enable row level security;
alter table user_stats enable row level security;
alter table user_earned_titles enable row level security;
alter table user_chronicle enable row level security;
alter table user_achievements enable row level security;
alter table user_skill_nodes enable row level security;
alter table quests enable row level security;
alter table goals enable row level security;
alter table goal_stages enable row level security;
alter table goal_tasks enable row level security;

create policy "Users can read their profile" on users for select using (id = auth.uid()::text);
create policy "Users can create their profile" on users for insert with check (id = auth.uid()::text);
create policy "Users can update their profile" on users for update using (id = auth.uid()::text) with check (id = auth.uid()::text);
create policy "Users can delete their profile" on users for delete using (id = auth.uid()::text);

create policy "Users manage stats" on user_stats for all using (user_id = auth.uid()::text) with check (user_id = auth.uid()::text);
create policy "Users manage earned titles" on user_earned_titles for all using (user_id = auth.uid()::text) with check (user_id = auth.uid()::text);
create policy "Users manage chronicle" on user_chronicle for all using (user_id = auth.uid()::text) with check (user_id = auth.uid()::text);
create policy "Users manage achievements" on user_achievements for all using (user_id = auth.uid()::text) with check (user_id = auth.uid()::text);
create policy "Users manage skill nodes" on user_skill_nodes for all using (user_id = auth.uid()::text) with check (user_id = auth.uid()::text);
create policy "Users manage quests" on quests for all using (user_id = auth.uid()::text) with check (user_id = auth.uid()::text);
create policy "Users manage goals" on goals for all using (user_id = auth.uid()::text) with check (user_id = auth.uid()::text);

create policy "Users manage goal stages" on goal_stages
for all
using (exists (select 1 from goals where goals.id = goal_stages.goal_id and goals.user_id = auth.uid()::text))
with check (exists (select 1 from goals where goals.id = goal_stages.goal_id and goals.user_id = auth.uid()::text));

create policy "Users manage goal tasks" on goal_tasks
for all
using (exists (select 1 from goals where goals.id = goal_tasks.goal_id and goals.user_id = auth.uid()::text))
with check (exists (select 1 from goals where goals.id = goal_tasks.goal_id and goals.user_id = auth.uid()::text));
